# Generated by Django 4.0.2 on 2022-02-12 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='judge',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
