# Generated by Django 4.0.2 on 2022-02-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_submissions_param1_submissions_param2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
