# Generated by Django 4.0.2 on 2022-02-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_judgement_judge_alter_judgement_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='param1',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='param2',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='param3',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='total',
        ),
    ]
