# Generated by Django 4.0.2 on 2022-02-25 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_submissions_param1_remove_submissions_param2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='param4',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='QUALITY OF PRESENTATION'),
        ),
        migrations.AddField(
            model_name='judgement',
            name='param5',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='RELEVANCE TO PRIMARY TRACKS'),
        ),
        migrations.AddField(
            model_name='judgement',
            name='param6',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='RELEVANCE TO SECONDARY TRACK'),
        ),
        migrations.AddField(
            model_name='submissions',
            name='primary_track',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='submissions',
            name='secondary_track',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='param1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='ORIGINALITY OF IDEA/ ADVANCEMENTS IN THE FIELD'),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='param2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='BUSINESS VALUE / SOCIETAL IMPACT'),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='param3',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='IMPLEMENTATION OF IDEA'),
        ),
    ]
